name: Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run Build
        run: |
          # Najdeme absolutní cestu ke složce s projektem
          REQ_PATH=$(find . -name "requirements.txt" | head -n 1)
          MAIN_DIR=$(dirname "$REQ_PATH")
          cd "$MAIN_DIR"
          
          # Teď už jsme stoprocentně u souborů
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python main.py --arch x64 --release-type retail --magisk-ver stable --gapps-brand MindTheGapps --root-sol magisk
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WSA-Package
          path: "**/out/*.zip"
