name: Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run Build
        run: |
          # Jdeme přímo do složky, kde je projekt
          cd MagiskOnWSALocal/MagiskOnWSALocal || cd MagiskOnWSALocal || true
          # Teď už jsme tam, kde jsou soubory
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python main.py --arch x64 --release-type retail --magisk-ver stable --gapps-brand MindTheGapps --root-sol magisk
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: WSA-Package
          path: "**/out/*.zip"
          # Nainstaluje závislosti a spustí build
          pip install -r requirements.txt
          python main.py --arch x64 --release-type retail --magisk-ver stable --gapps-brand MindTheGapps --root-sol magisk
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: WSA-Package
          path: "**/out/*.zip"
