name: Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run Build
        run: |
          # 1. Najdeme requirements a nainstalujeme je
          REQ_FILE=$(find . -name "requirements.txt" | head -n 1)
          pip install -r "$REQ_FILE"
          
          # 2. Najdeme složku se skripty a vlezeme do ní
          cd $(dirname $(find . -name "main.py" | head -n 1))
          
          # 3. Spustíme to přímo z té složky
          python main.py --arch x64 --release-type retail --magisk-ver stable --gapps-brand MindTheGapps --root-sol magisk
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WSA-Package
          path: "**/out/*.zip"
