name: Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run Build
        run: |
          # Najde cestu k main.py a uloží ji
          SCRIPT_PATH=$(find . -name "main.py" | head -n 1)
          # Najde složku, kde main.py leží
          SCRIPT_DIR=$(dirname "$SCRIPT_PATH")
          # Přejde do té složky
          cd "$SCRIPT_DIR"
          # Nainstaluje potřebné věci a spustí to
          pip install -r requirements.txt
          python main.py --arch x64 --release-type retail --magisk-ver stable --gapps-brand MindTheGapps --root-sol magisk
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: WSA-Package
          path: "**/out/*.zip"
